import test from 'node:test';
import assert from 'node:assert/strict';
import {deflateRawSync} from 'node:zlib';
import {SCENE,point,rectangle,validBox,pngDimensions,crc32,extractC05,exportReview} from '../docs/core.js';
export function zip(entries){const chunks=[],central=[];let offset=0;for(const {name,bytes,method=0} of entries){const n=Buffer.from(name),data=method===8?deflateRawSync(bytes):bytes,h=Buffer.alloc(30);h.writeUInt32LE(0x04034b50);h.writeUInt16LE(20,4);h.writeUInt16LE(method,8);h.writeUInt32LE(crc32(bytes),14);h.writeUInt32LE(data.length,18);h.writeUInt32LE(bytes.length,22);h.writeUInt16LE(n.length,26);chunks.push(h,n,data);const c=Buffer.alloc(46);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(20,4);c.writeUInt16LE(20,6);c.writeUInt16LE(method,10);c.writeUInt32LE(crc32(bytes),16);c.writeUInt32LE(data.length,20);c.writeUInt32LE(bytes.length,24);c.writeUInt16LE(n.length,28);c.writeUInt32LE(offset,42);central.push(c,n);offset+=h.length+n.length+data.length;}const directory=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(directory.length,12);end.writeUInt32LE(offset,16);return new Uint8Array(Buffer.concat([...chunks,directory,end])).buffer;}
function pngHeader(w=1280,h=576){const a=Buffer.alloc(33);a.set([137,80,78,71,13,10,26,10]);a.writeUInt32BE(13,8);a.write('IHDR',12);a.writeUInt32BE(w,16);a.writeUInt32BE(h,20);return a;}
test('PNG dimensions use untouched original coordinates and reject other content',()=>{assert.deepEqual(pngDimensions(pngHeader()),{width:1280,height:576});assert.deepEqual(pngDimensions(pngHeader(640,288)),{width:640,height:288});assert.throws(()=>pngDimensions(Buffer.from('invalid')));});
test('coordinate transform reverses zoom/pan and clamps to original image',()=>{for(const scale of [.25,.7,1,4,12])for(const x of [0,17.5,640,1280])for(const y of [0,12.5,288,576]){const t={scale,x:-200,y:31};const p=point(x*scale+t.x,y*scale+t.y,t);assert.ok(Math.abs(p.x-x)<1e-9&&Math.abs(p.y-y)<1e-9);}assert.deepEqual(point(-1,9999,{x:0,y:0,scale:1}),{x:0,y:576});});
test('reverse drawing and box boundaries',()=>{assert.deepEqual(rectangle({x:200,y:150},{x:100,y:50}),{x:100,y:50,width:100,height:100});assert.ok(validBox({x:0,y:0,width:1280,height:576}));for(const b of [{x:-1,y:0,width:1,height:1},{x:1280,y:0,width:1,height:1},{x:0,y:0,width:0,height:1},{x:0,y:0,width:Infinity,height:1}])assert.ok(!validBox(b));});
test('ZIP locates only exact C05 entry without reading proposals',async()=>{const bytes=pngHeader();for(const method of [0,8]){const z=zip([{name:'proposals.json',bytes:Buffer.from('do not import')},{name:'frames/C05_frame_23835.png',bytes,method}]);const result=await extractC05(z);assert.deepEqual(result.bytes,new Uint8Array(bytes));assert.equal(result.path,'frames/C05_frame_23835.png');}});
test('ZIP rejects absent, duplicate, truncated and corrupted C05',async()=>{const e={name:'C05_frame_23835.png',bytes:pngHeader()};await assert.rejects(extractC05(zip([{...e,name:'C04.png'}])));await assert.rejects(extractC05(zip([e,e])));const z=zip([e]);await assert.rejects(extractC05(z.slice(0,-5)));const corrupt=new Uint8Array(z);corrupt[30+e.name.length]^=1;await assert.rejects(extractC05(corrupt.buffer),/CRC/);});
test('individual provisional export preserves hash, provenance, reviewers and geometry',()=>{const source={width:1280,height:576,sha256:'a'.repeat(64),filename:'C05_frame_23835.png',provenance:'local synthetic test'};const boxes=[{id:'B1',category:'visible_body',x:13.5,y:20,width:100,height:80,certainty:'supported',note:'visible only'},{id:'B2',category:'IGNORE',x:110,y:30,width:40,height:25,certainty:'approximate',note:'uncertain'}];for(const reviewer of ['R1','R2','R3','TEST']){const data=JSON.parse(JSON.stringify(exportReview({reviewer,source,boxes,coverage:'partial',notes:'gap'})));assert.equal(data.reviewer,reviewer);assert.equal(data.canonicalGroundTruth,false);assert.equal(data.status,'provisional_unvalidated');assert.equal(data.scene.frameIndex,23835);assert.equal(data.scene.timestampSeconds,794.5);assert.deepEqual(data.boxes[0].xyxy,[13.5,20,113.5,100]);assert.equal(data.source.sha256,source.sha256);assert.ok(!('heroId' in data.boxes[0]));}assert.throws(()=>exportReview({reviewer:'R4',source,boxes,coverage:'partial'}));assert.throws(()=>exportReview({reviewer:'R1',source:{...source,sha256:'bad'},boxes,coverage:'partial'}));assert.throws(()=>exportReview({reviewer:'R1',source,boxes,coverage:''}));});
