import {scene,manifestSource,syntheticSource} from './fixtures.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {zip} from './fixtures.js';
import {point,rectangle,validBox,pngDimensions,crc32,extractPNG,exportReview,conferRegion} from '../docs/core.js';

function pngHeader(w=1280,h=576){const a=Buffer.alloc(33);a.set([137,80,78,71,13,10,26,10]);a.writeUInt32BE(13,8);a.write('IHDR',12);a.writeUInt32BE(w,16);a.writeUInt32BE(h,20);return a;}
test('PNG dimensions use untouched original coordinates and reject other content',()=>{assert.deepEqual(pngDimensions(pngHeader()),{width:1280,height:576});assert.deepEqual(pngDimensions(pngHeader(640,288)),{width:640,height:288});assert.throws(()=>pngDimensions(Buffer.from('invalid')));});
test('coordinate transform reverses zoom/pan and clamps to original image',()=>{for(const scale of [.25,.7,1,4,12])for(const x of [0,17.5,640,1280])for(const y of [0,12.5,288,576]){const t={scale,x:-200,y:31};const p=point(x*scale+t.x,y*scale+t.y,t);assert.ok(Math.abs(p.x-x)<1e-9&&Math.abs(p.y-y)<1e-9);}assert.deepEqual(point(-1,9999,{x:0,y:0,scale:1}),{x:0,y:576});});
test('reverse drawing and box boundaries',()=>{assert.deepEqual(rectangle({x:200,y:150},{x:100,y:50}),{x:100,y:50,width:100,height:100});assert.ok(validBox({x:0,y:0,width:1280,height:576}));for(const b of [{x:-1,y:0,width:1,height:1},{x:1280,y:0,width:1,height:1},{x:0,y:0,width:0,height:1},{x:0,y:0,width:Infinity,height:1}])assert.ok(!validBox(b));});
test('ZIP locates only exact SYN_A entry without reading proposals',async()=>{const bytes=pngHeader();for(const method of [0,8]){const z=zip([{name:'proposals.json',bytes:Buffer.from('do not import')},{name:'frames/synthetic-a.png',bytes,method}]);const result=await extractPNG(z,'frames/synthetic-a.png');assert.deepEqual(result.bytes,new Uint8Array(bytes));assert.equal(result.path,'frames/synthetic-a.png');}});
test('ZIP rejects absent, duplicate, truncated and corrupted SYN_A',async()=>{const e={name:'synthetic-a.png',bytes:pngHeader()};await assert.rejects(extractPNG(zip([{...e,name:'other.png'}]),e.name));await assert.rejects(extractPNG(zip([e,e]),e.name));const z=zip([e]);await assert.rejects(extractPNG(z.slice(0,-5),e.name));const corrupt=new Uint8Array(z);corrupt[30+e.name.length]^=1;await assert.rejects(extractPNG(corrupt.buffer,e.name),/CRC/);});
test('individual provisional export preserves hash, provenance, reviewers and geometry',()=>{const source=syntheticSource;const boxes=[{id:'B1',category:'visible_body',x:13.5,y:20,width:100,height:80,certainty:'supported',note:'visible only'},{id:'B2',category:'IGNORE',x:110,y:30,width:40,height:25,certainty:'approximate',note:'uncertain'}];for(const reviewer of ['R1','R2','R3','TEST']){boxes.forEach(b=>conferRegion(b,'keep',reviewer));const data=JSON.parse(JSON.stringify(exportReview({scene,manifestSource,reviewer,source,boxes,coverage:'partial',notes:'gap'})));assert.equal(data.reviewer,reviewer);assert.equal(data.canonicalGroundTruth,false);assert.equal(data.status,'provisional_unvalidated');assert.equal(data.scene.frameIndex,30);assert.equal(data.scene.timestampSeconds,1);assert.deepEqual(data.boxes[0].xyxy,[13.5,20,113.5,100]);assert.equal(data.source.sha256,source.sha256);assert.ok(!('heroId' in data.boxes[0]));}assert.throws(()=>exportReview({scene,manifestSource,reviewer:'R4',source,boxes,coverage:'partial'}));assert.throws(()=>exportReview({scene,manifestSource,reviewer:'R1',source:{...source,sha256:'bad'},boxes,coverage:'partial'}));assert.throws(()=>exportReview({scene,manifestSource,reviewer:'R1',source,boxes,coverage:''}));});
